using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using NgalaFarms.Application;
using NgalaFarms.Domain.Entities;
using NgalaFarms.Infrastructure;
using NgalaFarms.Infrastructure.Data;
using NgalaFarms.Infrastructure.Seed;
using System.Text.Json.Serialization;

AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
        options.JsonSerializerOptions.DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull;
        options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
    });
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Ngala Farms API", Version = "v1" });
    c.AddSecurityDefinition("Bearer", new OpenApiSecurityScheme
    {
        In = ParameterLocation.Header,
        Description = "Enter: Bearer {token}",
        Name = "Authorization",
        Type = SecuritySchemeType.ApiKey
    });
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        { new OpenApiSecurityScheme { Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" } }, Array.Empty<string>() }
    });
});

builder.Services.AddInfrastructure(builder.Configuration);
builder.Services.AddApplication();

builder.Services.AddCors(options =>
{
    var renderFrontendUrl = Environment.GetEnvironmentVariable("FRONTEND_URL");
    var allowedOrigins = new[]
    {
        "http://localhost:5173",
        "http://localhost:3000",
        "http://localhost:5174",
        renderFrontendUrl
    }
    .Where(origin => !string.IsNullOrWhiteSpace(origin))
    .Select(origin => origin!);

    options.AddPolicy("NgalaFarmsPolicy", policy =>
        policy.WithOrigins(allowedOrigins.ToArray())
        .AllowAnyMethod()
        .AllowAnyHeader()
        .AllowCredentials());
});

builder.Services.AddSignalR();

var app = builder.Build();

// Seed database
using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<NgalaFarmsDbContext>();
    var userManager = scope.ServiceProvider.GetRequiredService<UserManager<ApplicationUser>>();
    var roleManager = scope.ServiceProvider.GetRequiredService<RoleManager<IdentityRole>>();
    await context.Database.MigrateAsync();
    await context.Database.ExecuteSqlRawAsync("""
        DO $$
        DECLARE column_record record;
        BEGIN
            FOR column_record IN
                                SELECT c.table_name, c.column_name
                                FROM information_schema.columns c
                                WHERE c.table_schema = 'public'
                                    AND c.data_type = 'integer'
                  AND (
                      column_name LIKE 'Is%'
                      OR column_name LIKE '%Confirmed'
                      OR column_name LIKE '%Enabled'
                  )
            LOOP
                EXECUTE format(
                    'ALTER TABLE %I ALTER COLUMN %I TYPE boolean USING %I <> 0',
                    column_record.table_name,
                    column_record.column_name,
                    column_record.column_name);
            END LOOP;
        END $$;
        """);
    await context.Database.ExecuteSqlRawAsync("""
        DO $$
        DECLARE key_record record;
        BEGIN
            FOR key_record IN
                SELECT tc.table_name, kcu.column_name
                FROM information_schema.table_constraints tc
                JOIN information_schema.key_column_usage kcu
                  ON tc.constraint_name = kcu.constraint_name
                 AND tc.table_schema = kcu.table_schema
                JOIN information_schema.columns c
                  ON c.table_schema = kcu.table_schema
                 AND c.table_name = kcu.table_name
                 AND c.column_name = kcu.column_name
                WHERE tc.constraint_type = 'PRIMARY KEY'
                  AND tc.table_schema = 'public'
                  AND c.data_type = 'integer'
                  AND c.column_default IS NULL
                  AND c.is_identity = 'NO'
            LOOP
                EXECUTE format(
                    'ALTER TABLE %I ALTER COLUMN %I ADD GENERATED BY DEFAULT AS IDENTITY',
                    key_record.table_name,
                    key_record.column_name);
            END LOOP;
        END $$;
        """);
    var normalizedColumns = new HashSet<string>(StringComparer.Ordinal);
    foreach (var entityType in context.Model.GetEntityTypes())
    {
        var tableName = entityType.GetTableName();
        var schemaName = entityType.GetSchema() ?? "public";
        if (tableName == null)
            continue;

        foreach (var property in entityType.GetProperties())
        {
            var propertyType = Nullable.GetUnderlyingType(property.ClrType) ?? property.ClrType;
            var postgresType = propertyType == typeof(DateTime) || propertyType == typeof(DateTimeOffset)
                ? "timestamp with time zone"
                : propertyType == typeof(decimal)
                    ? "numeric"
                    : null;
            var columnName = property.GetColumnName();
            if (postgresType == null || columnName == null)
                continue;

            var key = $"{schemaName}.{tableName}.{columnName}.{postgresType}";
            if (!normalizedColumns.Add(key))
                continue;

            static string QuoteIdentifier(string value) => $"\"{value.Replace("\"", "\"\"")}\"";
            static string QuoteLiteral(string value) => $"'{value.Replace("'", "''")}'";
            var quotedTable = QuoteIdentifier(tableName);
            var quotedColumn = QuoteIdentifier(columnName);
            var tableLiteral = QuoteLiteral(tableName);
            var columnLiteral = QuoteLiteral(columnName);
            await context.Database.ExecuteSqlRawAsync($"""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = '{schemaName}'
                          AND table_name = {tableLiteral}
                          AND column_name = {columnLiteral}
                          AND data_type = 'text') THEN
                        EXECUTE 'ALTER TABLE {quotedTable} ALTER COLUMN {quotedColumn} TYPE {postgresType} USING NULLIF({quotedColumn}, '''')::{postgresType}';
                    END IF;
                END $$;
                """);
        }
    }
    await DatabaseSeeder.SeedAsync(context, userManager, roleManager);
}

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseStaticFiles();
app.UseCors("NgalaFarmsPolicy");
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
app.MapGet("/", () => Results.Ok(new
{
    name = "Ngala Farms API",
    status = "running"
}));
app.MapGet("/health", () => Results.Ok(new { status = "healthy" }));

app.Run();
